### ISSUE TITLE
syntax highlighting is incorrect for comments in CSS

### ISSUE THREAD

**Issue by trafnar** [imba/vscode-imba#110]
extension version: v3.0.5

<img width="218" alt="image" src="https://user-images.githubusercontent.com/6732/131721009-812cf053-4e36-4862-b306-7687aa1ccf29.png">

This comment is not colored correctly
`.foo # bar`

This one is
`.foo bgc:red # bar`

**Comment by trafnar** [comment]
Oh.. actually this seems to be an imba bug or limitation, not a tooling bug. I thought at first that it was interpreted as a comment despite not being highlighted correctly, but it is actually producing an error.

**Comment by somebee** [comment]
Fix will be released in next alpha :)
