### ISSUE TITLE
Language Server crashing

### ISSUE THREAD

**Issue by devhammed** [imba/vscode-imba#29]
Hello, I am just starting to use Imba today...after installing the CLI and the VS Code extension, I opened a Imba file and the extension said the language server has crashed, I restarted up to 5 times and the same thing happens in all the restarts.

![Screenshot from 2020-04-28 18-17-13](https://user-images.githubusercontent.com/22827908/80517969-c65b2200-897d-11ea-9bd2-0b379ccf8306.png)

**Comment by somebee** [comment]
Thanks for reporting. Will push a new version later today that hopefully fixes the problem. It is still very unstable, but should work :)

**Comment by devhammed** [comment]
Hello @somebee , have you fixed this?

**Comment by somebee** [comment]
I haven't experienced this yet with the latest version, but I'll keep the issue open for a week or two in case someone else starts experiencing this again.

**Comment by devhammed** [comment]
@somebee YES!

It is no longer crashing.

**Comment by somebee** [comment]
Great. I'll close this then. We'll open a new issue if it happens again :)
