### ISSUE TITLE
Errors in highlighting

### ISSUE THREAD

**Issue by altteo** [imba/vscode-imba#31]
![image](https://user-images.githubusercontent.com/1933862/86163799-71708f00-bb19-11ea-9cb2-5363e4a80cc1.png)

**Comment by altteo** [comment]
D:\_Projects\projector\app.imba

**Comment by altteo** [comment]
[app.imba.txt](https://github.com/imba/vscode-imba/files/4853798/app.imba.txt)

**Comment by altteo** [comment]
Code example in the file in previous post.

**Comment by altteo** [comment]
After a little digging it seams that this error appeared because of copy-paste.
The code was pasted with dot-indents. And coloring stayed broken even after swapping dots to tabs.
It helped to cut-paste blocks of code right inplace.

**Comment by altteo** [comment]
After more digging the problem was found with `new` statement. As I understand now it should be used as in js: `new Someclass()`.
But `new` without brackets or exclamation mark ruins highlighing. And more over to fix it, we need to reload vs code window (or restart it).

**Comment by altteo** [comment]
My mistake. New syntax like  `new Koa!` do not ruin highlighting. But old one `Koa.new` ruins and doesn't autofix (after syntax is corrected).

**Comment by somebee** [comment]
The latest version should be much better at highlighting semantic tokens without screwing up the ranges :)
