### ISSUE TITLE
### Comment blocks syntax colors are broken

### ISSUE THREAD

**Issue by ericvida** [imba/vscode-imba#9]
For me the syntax colors are broken on comment blocks in VS Code. 
Everything works fine with css comment blocks thought.
###

![image](https://user-images.githubusercontent.com/13579055/74539167-6f06f300-4ef2-11ea-94c6-2e250ca7adc8.png)

**Comment by aalemayhu** [comment]
This has been fixed in the brand new Name:  https://marketplace.visualstudio.com/items?itemName=scrimba.vsimba
