### ISSUE TITLE
Typing @click=( autocompletes to @click=render()

### ISSUE THREAD

**Issue by trafnar** [imba/vscode-imba#92]
after typing `<button @click=(`, it autocompletes to `<button @click=render()>` unless I press escape first.

**Comment by trafnar** [comment]
v 3.0.2

**Comment by trafnar** [comment]
this also happend when I typed: `<Foo ranges=[` it autocompletes to `<Foo ranges=render`

**Comment by somebee** [comment]
Great, keep these coming! :) We may consider not showing completions automatically after `=`, or rather add a blank completion that is preselected - that does not use these triggers. Another solution all together may be to only add the additional trigger characters (like `(`, `[`, `.`) after you've typed at least one character.

**Comment by somebee** [comment]
This is fixed in the latest release (v3.0.3)
